apiVersion: v1
kind: Service
metadata:
  name: template-agent
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: template-agent-tls
  labels:
    app: template-agent
    component: agent
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: template-agent
    component: agent
